FROM maven:3.9.9-eclipse-temurin-23 AS build
COPY . .
RUN mvn clean package -DskipTests

FROM eclipse-temurin:23-jdk
COPY --from=build /target/Banking-SpringBoot-0.0.1-SNAPSHOT.jar Banking-SpringBoot.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "demo.jar"]